version: "3.8"

services:
  db:
    image: postgres:15.6-alpine3.19
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  rabbitmq:
    image: rabbitmq:3.13.1-management-alpine
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_PLUGIN_PORT}:15672"

volumes:
  postgres_data:
